services:
  sentinelops-api:
    build:
      context: ./SentinelOps.Api
    container_name: sentinelops-api
    restart: unless-stopped
    ports:
      - "5283:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
      SENTINELOPS_DB_PATH: /data/sentinelops.db
      FRONTEND_ORIGINS: http://localhost:5173,http://sentinelpi:5173
    volumes:
      - sentinelops-data:/data

volumes:
  sentinelops-data:
